// src/services/pdfService.ts
export class PDFService {
  static generateSWCorpReport(reportData: any): void {
    const content = `
SWCorp Malaysia Food Redistribution Impact Report
Period: ${reportData.period}

KEY METRICS:
- Food Saved: ${reportData.foodSavedKg} kg
- Water Saved: ${reportData.waterSavedKL} kL  
- CO2 Reduced: ${reportData.co2ReducedTons} tons
- People Helped: ${reportData.peopleHelped.toLocaleString()}
- Economic Value: ${reportData.economicValue}
- Active Donors: ${reportData.activeDonors}
- Completed Campaigns: ${reportData.completedCampaigns}

EXECUTIVE SUMMARY:
${reportData.analysis}

Generated by Food Redistribution Platform AI Assistant
${new Date().toLocaleDateString()}
    `.trim();

    this.downloadTextFile(content, `SWCorp_Report_${new Date().toISOString().split('T')[0]}.txt`);
  }

  static generateUserReport(userData: any): void {
    const content = `
User Risk Assessment Report
Generated: ${new Date().toLocaleDateString()}

PROBLEMATIC USERS:
${userData.problemUsers.map((user: any, index: number) => `
${index + 1}. ${user.name} (${user.role})
   - Risk Level: ${user.riskLevel}
   - Reports: ${user.reportCount}
   - Avg Rating: ${user.averageRating}/5
   - Warning Signs: ${user.warningSigns.join(', ')}
`).join('')}

Total Users Requiring Attention: ${userData.problemUsers.length}
    `.trim();

    this.downloadTextFile(content, `User_Risk_Report_${new Date().toISOString().split('T')[0]}.txt`);
  }

  private static downloadTextFile(content: string, filename: string): void {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}